
    tailwind.config = {
        darkMode: "class",
    theme: {
        extend: {
        colors: {
        outline: "#75777e",
    "on-secondary-container": "#00217a",
    "on-primary-fixed": "#0d1c32",
    error: "#ba1a1a",
    "secondary-fixed": "#dde1ff",
    "surface-bright": "#f8f9ff",
    "surface-container": "#e5eeff",
    secondary: "#3755c3",
    "on-tertiary-fixed": "#001e2c",
    "on-secondary": "#ffffff",
    "on-secondary-fixed-variant": "#173bab",
    "primary-container": "#0d1c32",
    "on-surface-variant": "#44474d",
    "on-surface": "#0b1c30",
    "primary-fixed-dim": "#b9c7e4",
    surface: "#f8f9ff",
    "tertiary-container": "#001e2c",
    "primary-fixed": "#d6e3ff",
    "outline-variant": "#c5c6cd",
    "on-tertiary-container": "#008ebf",
    "secondary-container": "#708cfd",
    "surface-tint": "#515f78",
    primary: "#000000",
    "surface-container-highest": "#d3e4fe",
    "tertiary-fixed": "#c4e7ff",
    "inverse-on-surface": "#eaf1ff",
    "surface-dim": "#cbdbf5",
    "inverse-primary": "#b9c7e4",
    "on-background": "#0b1c30",
    "surface-container-low": "#eff4ff",
    "on-primary-container": "#76849f",
    "on-tertiary-fixed-variant": "#004c69",
    background: "#f8f9ff",
    "secondary-fixed-dim": "#b8c4ff",
    tertiary: "#000000",
    "on-error-container": "#93000a",
    "inverse-surface": "#213145",
    "on-primary": "#ffffff",
    "surface-variant": "#d3e4fe",
    "on-tertiary": "#ffffff",
    "surface-container-high": "#dce9ff",
    "on-secondary-fixed": "#001453",
    "tertiary-fixed-dim": "#7bd0ff",
    "on-primary-fixed-variant": "#39475f",
    "surface-container-lowest": "#ffffff",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
            },
    borderRadius: {
        DEFAULT: "0.25rem",
    lg: "0.5rem",
    xl: "0.75rem",
    full: "9999px",
            },
    spacing: {
        "stack-lg": "32px",
    "container-max": "1280px",
    "stack-md": "16px",
    gutter: "24px",
    "margin-mobile": "16px",
    "stack-sm": "8px",
    "margin-desktop": "48px",
            },
    fontFamily: {
        "label-md": ["Inter"],
    "headline-lg": ["Inter"],
    "headline-xl": ["Inter"],
    "headline-md": ["Inter"],
    "body-md": ["Inter"],
    "headline-xl-mobile": ["Inter"],
    "body-lg": ["Inter"],
            },
    fontSize: {
        "label-md": [
    "14px",
    {
        lineHeight: "20px",
    letterSpacing: "0.05em",
    fontWeight: "600",
                },
    ],
    "headline-lg": [
    "32px",
    {
        lineHeight: "40px",
    letterSpacing: "-0.01em",
    fontWeight: "700",
                },
    ],
    "headline-xl": [
    "48px",
    {
        lineHeight: "56px",
    letterSpacing: "-0.02em",
    fontWeight: "700",
                },
    ],
    "headline-md": [
    "24px",
    {lineHeight: "32px", fontWeight: "600" },
    ],
    "body-md": ["16px", {lineHeight: "24px", fontWeight: "400" }],
    "headline-xl-mobile": [
    "32px",
    {lineHeight: "40px", fontWeight: "700" },
    ],
    "body-lg": ["18px", {lineHeight: "28px", fontWeight: "400" }],
            },
          },
        },
      };